  - name: installing maven
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - maven
    - mysql

  - name: installing dependencies
    ansible.builtin.command: mvn clean package
    args:
        chdir: /app


  - name: move the jar files
    ansible.builtin.command: mv target/{{ component }}-1.0.jar {{ component }}.jar
    args:
        chdir: /app