
  - name: diabale nginx
    ansible.builtin.command: dnf module disable nginx -y
 
  - name: enabl nginx
    ansible.builtin.command: dnf module enable nginx:1.24 -y

  - name: install nginx
    ansible.builtin.package:
      name: nginx 
      state: present

  - name: remove the html content
    ansible.builtin.file:
      state: absent
      path: usr/share/nginx/html/

  - name: creating the html directory
    ansible.builtin.file:
      state: directory
      path: sr/share/nginx/html/

  - name: downlaod the frontend
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: unzip the user file
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html 
      remote_src: true

  - name: remobing default configuration
    ansible.builtin.file:
      state: absent
      path: /etc/nginx/nginx.conf

  - name: copying nginx conf file
    ansible.builtin.template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf

  - name: restart ngix
    ansible.builtin.service:
      state: restarted
      name: nginx 
      enabled: yes
    notify: restart nginx

  


  

  

  
 