  - name: copy rabbitmq repo
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo

  - name: install mongodb
    ansible.builtin.package:
      name: rabbitmq-server
      state: present 

  - name: start and enable service
    ansible.builtin.service:
      name: rabbitmq-server
      state: started
      enabled: yes

  - name: adding roboshop user and giving permissions
    community.rabbitmq.rabbitmq_user:
      user: roboshop
      password: roboshop123
      permissions:
        - vhost: /
          configure_priv: .*
          read_priv: .*
          write_priv: .*
      state: present