    - name: adding robosho user
      ansible.builtin.user:
        name: roboshop
        comment: roboshop system user
        shell: /sbin/nologin
        system: true
        home: /app
# safe to remove the directory, 2 nd time we run it will download freshly. if does not exist no error.
    - name: delete the directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: creating directory
      ansible.builtin.file:
        state: directory
        path: /app

    - name: removing the {{ component }} file
      ansible.builtin.file:
        path: /tmp/{{ component }}.zip 
        state: absent

    - name: downloading {{ component }} application
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip 
        dest: /tmp/{{ component }}.zip    
    
    - name: unzipping the {{ component }} application
      ansible.builtin.unarchive:
        src: /tmp/{{ component }}.zip
        dest: /app
        remote_src: yes